<?php
/**
 * @file
 * Logic to handle the MyCalendarTabs module.
 */

/**
 * Declares what blocks are provided by MyCalendarTabs.
 *
 * Implements hook_block_info().
 */
function mycalendartabs_block_info() {
  $block['mycalendartabs'] = array(
    'info' => t('My Calendar Tabs'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $block;
}

/**
 * Defines what mycalendartabs is going to look like.
 *
 * Implements hook_block_view().
 */
function mycalendartabs_block_view($delta = '') {
  $block = array();
  
  switch($delta) {
    case ('mycalendartabs'):
      $vars = array(
        'month' => '<span id="mycalendartabs-month" class="selected">Month</span>',
        'year' => '<span id="mycalendartabs-year">Year</span>',
        'upcoming' => '<span id="mycalendartabs-upcoming">Upcoming</span>',
      );
      $block['subject'] = '';
      $block['content'] = theme('mycalendartabs_output', $vars);
      break;
  }
  
  return $block;
}

/**
 * Themes the block using hook_theme to specify a theme function and implements
 * it using theme_mythemefunction.
 *
 * Implements hook_theme().
 */
function mycalendartabs_theme() {
  global $base_path;
  
  // theme block with template file
  return array(
    'mycalendartabs_output' => array(
      'template' => 'output',
      'path' => drupal_get_path('module', 'mycalendartabs') . '/templates',
      'type' => 'theme',
      'variables' => array(
        'month' => NULL,
        'year' => NULL,
        'upcoming' => NULL,
      ),
    ),
  );
}