<?php

function myeventattendance_block_info() {
  $block['myeventattendance'] = array(
    'info' => t('My Event Attendance'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $block;
}

function myeventattendance_block_view($delta = '') {
  global $user;
  $block = array();
  $node = menu_get_object();
  
  // Instantiate flags
  $attending = flag_get_flag('attending');
  $responded = flag_get_flag('responded');
  
  // Create links for flagging/unflagging.
  $will_attend_link = flag_create_link('attending', $node->nid);
  
  // Set variables to display status of flag.
  $status = 'Error calling flag_get_flag.';
  $will_attend_status = '';
  $will_not_attend_status = '';
  
  // Set links for will/will not attend
  $will_attend_link = 'Will Attend';
  $will_not_attend_link = 'Will Not Attend';

  // Check that the flags were properly instantiated.
  if($attending && $responded) {
    
    // Case for if user has responded.
    if($responded->is_flagged($node->nid, $user->uid)) {
      
      // Case for if user has selected 'Will Attend'.
      if($attending->is_flagged($node->nid, $user->uid)) {
        $status = 'You will attend.';
        $will_attend_status = 'selected';
        $will_attend_link = flag_create_link('attending', $node->nid);
      }
      
      // Case for if user has selected 'Will Not Attend'.
      else {
        $status = 'You will not attend.';
        $will_not_attend_status = 'selected';
        $will_not_attend_link = flag_create_link('attending', $node->nid);
      }
    }
    
    // Case for if user has not responded.
    else {
      $status = 'You have not yet responded.';
      $will_attend_link = flag_create_link('attending', $node->nid);
      $will_not_attend_link = flag_create_link('responded', $node->nid);
    }
  }
  
  switch($delta) {
    case ('myeventattendance'):
      $vars = array(
        'willAttend' => '<span id="myeventattendance-will" class="' . $will_attend_status . '">' . $will_attend_link . '</span>',
        'willNotAttend' => '<span id="myeventattendance-wont" class="' . $will_not_attend_status . '">' . $will_not_attend_link . '</span>',
        'status' => $status,
      );
      $block['subject'] = '';
      $block['content'] = theme('myeventattendance_output', $vars);
      break;
  }
  
  return $block;
}

function myeventattendance_theme() {  
  return array(
    'myeventattendance_output' => array(
      'template' => 'output',
      'path' => drupal_get_path('module', 'myeventattendance') . '/templates',
      'type' => 'theme',
      'variables' => array(
        'willAttend' => NULL,
        'willNotAttend' => NULL,
        'status' => NULL,
      ),
    ),
  );
}

function myeventattendance_flag_flag($flag, $content_id, $account, $flagging) {
  flag('flag', 'responded', $node->nid);
}