<?php
  
/**
 *
 * Implementation of hook_views_api().
 */
function mymembership_views_api() {
  return array(
    'api' => 3,
    //'path' => drupal_get_path('module', 'mycommitteemembership') . '/includes/views',
    //'template path' => drupal_get_path('module', 'mycommitteemembership') . '/templates',
  );
}

/**
 * Implementation of hook_menu().
 */
function mymembership_menu() {
  $items = array();
  $items['board/committees/join'] = array(
    'title' => t('Join a Committee'),
    'description' => t('MyMembership committee request form.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mymembership_form'),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implementation of hook_form().
 */
function mymembership_form($form, &$form_state) {

  $users = array('0' => '-- Select a User --');

  $terms = array('0' => '-- Select a Committee --');
  $terms += taxonomy_allowed_values(field_info_field('field_member_committee'));

  $form['users'] = array(
    '#type' => 'select',
    '#description' => t('Please select a board member.'),
    '#default_value' => 0,
    '#options' => $users,
    '#required' => TRUE,
  );

  $form['committees'] = array(
    '#type' => 'select',
    '#title' => t('Please select the committee for this board member to join.'),
    '#description' => t('Excellent description of this select field.'),
    '#default_value' => 0,
    '#options' => $terms,
    '#required' => TRUE,
  );
  
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Submit Request'),
  );

  return $form;
}


/**
 * Implementation of hook_form_validate().
 */
function mymembership_form_validate($form, &$form_state) {
  
}

/**
 * Implementation of hook_form_submit().
 */
function mymembership_form_submit($form, &$form_state) {
  
}